truth</h3><p>Every vehicle’s operational context lives together.</p></div><div class="card outcome-card reveal delay-2"><strong>One</strong><h3>next action</h3><p>Every opportunity has clear ownership and timing.</p></div><div class="card outcome-card reveal delay-3"><strong>One</strong><h3>owner view</h3><p>Every risk and opportunity becomes easier to see.</p></div></div></div></section>
<section id="audit" class="section surface-section"><div class="container"><div class="grid grid-2" style="align-items:start"><div class="reveal"><div class="eyebrow">Free dealership systems audit</div><h2>Find where leads, stock and follow-up are slipping between systems.</h2><p class="lead">We will map the current journey from website enquiry to sales follow-up and show the operational gaps worth fixing first. No generic 40-page report and no obligation to replace everything.</p><div class="check-list"><div class="check">Lead-source and routing review</div><div class="check">Website-to-sales-floor journey</div><div class="check">Stock and reporting blind spots</div><div class="check">Recommended rollout priorities</div></div></div>{audit_form()}</div></div></section>
<section class="section"><div class="container"><div class="story-row"><div class="story-copy reveal"><div class="eyebrow">A fair comparison</div><h2>VMG built a mature South African DMS. DealershipCore is building the modern growth layer dealers are still missing.</h2><p class="lead">The strongest position is not to deny VMG’s depth in dealership administration, workshop and accounting. DealershipCore’s advantage is a connected cloud-first experience around website conversion, valuation funnels, lead accountability, automation and owner visibility.</p><div class="note">Our comparison page separates publicly documented VMG capabilities, DealershipCore launch capabilities and roadmap items. No invented weakness, no fake review scores.</div><div style="margin-top:26px"><a class="btn btn-secondary" href="/compare/vmg-alternative/">Compare DealershipCore and VMG <span class="arrow">→</span></a></div></div>{visual('owner')}</div></div></section>
<section class="section surface-section"><div class="narrow text-center"><div class="eyebrow">Frequently asked questions</div><h2>Clear answers before you change anything.</h2>{faq_block(home_faq)}</div></section>
{cta('Build the dealership operating system around the way your team really works.', 'Start with a free systems audit or request access to the founding dealer programme. We will identify what should connect first, what can remain in place and what DealershipCore should solve.')}
'''
write_pages = []
write_pages.append(('/', shell('Dealership Management and Growth Software South Africa', 'DealershipCore connects dealership stock, websites, valuation leads, sales follow-up, automation and owner reporting in one modern South African platform.', '/', home_body, faq=home_faq)))

# Platform page
platform_faq=[('Does DealershipCore include accounting?', 'Full accounting is not positioned as a launch module. DealershipCore can integrate around existing accounting processes while deeper financial modules remain part of the longer-term roadmap.'), ('Does it support workshops?', 'Workshop management is not a launch-strength claim. DealershipCore’s initial focus is dealership growth, stock, lead flow, website integration, valuation funnels and reporting.'), ('Can it work with our existing DMS?', 'Yes, subject to available APIs, exports and integration permissions. A staged rollout may be better than replacing every system at once.')]
platform_body = page_hero('The platform', 'The dealership growth operating system.', 'DealershipCore connects the customer journey, the vehicle record and the owner’s view—from online demand to the next action on the sales floor.', '/platform/', 'Built to connect, not confuse', 'The platform is structured around real dealership workflows rather than a collection of unrelated feature screens.') + f'''
<section class="section surface-section"><div class="container"><div class="story-row"><div class="story-copy reveal"><div class="eyebrow">One operating model</div><h2>Customer. Vehicle. Opportunity. Next action.</h2><p class="lead">Every DealershipCore module is designed around four connected records. The customer should not be duplicated. The vehicle should not have conflicting statuses. The opportunity should not disappear. The next action should never be invisible.</p><div class="check-list"><div class="check">A universal customer and lead record</div><div class="check">A connected vehicle and stock record</div><div class="check">A visible opportunity and pipeline state</div><div class="check">An accountable owner, deadline and outcome</div></div></div>{visual('pipeline')}</div></div></section>
<section class="section"><div class="container"><div class="eyebrow">Platform modules</div><h2>Everything needed to run a modern dealership growth workflow.</h2><div class="grid grid-3" style="margin-top:38px">''' + ''.join(f'<a class="card card-hover feature-card reveal" href="/features/{slug}/"><div class="card-number">{i:02}</div><h3>{data["eyebrow"]}</h3><p>{data["intro"]}</p><span class="text-link">Explore module <span class="arrow">→</span></span></a>' for i,(slug,data) in enumerate(FEATURES.items(),1)) + '''</div></div></section>
<section class="section surface-section"><div class="container"><div class="grid grid-2"><div class="reveal"><div class="eyebrow">Designed for daily use</div><h2>Fast enough for the sales floor. Clear enough for the owner.</h2><p class="lead">The uploaded product design standard has been translated into the platform concept: consistent navigation, actionable KPI cards, clear status language, loading and error states, role-based visibility, mobile-first workflows and persistent data—not decorative dashboard screens.</p></div><div class="card"><h3>Core UX principles</h3><div class="check-list"><div class="check">Urgent actions appear before decorative analytics.</div><div class="check">Every metric links to the underlying work.</div><div class="check">Every action confirms what changed.</div><div class="check">Every page includes empty, loading and error states.</div><div class="check">South African date, time, VAT and ZAR formatting.</div></div></div></div></div></section>
<section class="section"><div class="narrow text-center"><div class="eyebrow">Platform questions</div><h2>What DealershipCore is—and what it is not pretending to be.</h2>''' + faq_block(platform_faq) + '</div></section>' + cta()
write_pages.append(('/platform/', shell('DealershipCore Platform Overview', 'Explore the DealershipCore platform for dealership lead management, stock visibility, websites, valuation funnels, automation and owner reporting.', '/platform/', platform_body, active='/platform/', faq=platform_faq)))

# Feature pages
for slug,data in FEATURES.items():
    body = page_hero(data['eyebrow'], data['headline'], data['intro'], f'/fe