Number of dealership branches and workspaces</div><div class="check">Typical stock volume and data migration</div><div class="check">Number of users, teams and permission roles</div><div class="check">Required website, valuation and marketplace integrations</div><div class="check">Custom workflow, reporting and automation requirements</div></div></div><div class="card"><h3>Every proposal separates</h3><div class="check-list"><div class="check">Once-off implementation</div><div class="check">Monthly platform subscription</div><div class="check">Optional website or funnel build</div><div class="check">Third-party data and integration costs</div><div class="check">Roadmap items not included today</div></div></div></div></div></section>
<section class="section surface-section"><div class="narrow text-center"><div class="eyebrow">Pricing questions</div><h2>Know what is included before you commit.</h2>''' + faq_block(price_faq) + '</div></section>' + cta('Get a proposal built around the dealership you actually run.', 'The free systems audit identifies the first modules, required integrations and a practical rollout order before commercial scope is finalised.')
write_pages.append(('/pricing/', shell('DealershipCore Pricing and Founding Dealer Plans', 'Understand how DealershipCore pricing is scoped for independent dealerships and dealer groups across modules, branches, users, integrations and onboarding.', '/pricing/', pricing_body, active='/pricing/', faq=price_faq)))

# About
about_body = page_hero('About DealershipCore', 'Built from the belief that dealerships need connected growth systems—not more disconnected software.', 'DealershipCore is a South African dealership technology company creating one operating layer across valuation demand, dealership websites, stock visibility, lead follow-up and owner reporting.', '/about/', 'A product built around a real market gap', 'Traditional DMS tools are strong at administration. Marketing tools are strong at demand. DealershipCore connects the space between them.') + '''
<section class="section surface-section"><div class="container"><div class="story-row"><div class="story-copy"><div class="eyebrow">Why DealershipCore exists</div><h2>The deal is often lost between systems—not because the dealership did not care.</h2><p class="lead">A website creates an enquiry. A valuation tool captures a vehicle. A salesperson follows up. A manager checks the pipeline. An owner asks what happened. Too often, each step uses a different record.</p><p>DealershipCore is being built to make the customer, vehicle, opportunity and next action part of one visible operating story.</p></div>''' + visual('feed') + '''</div></div></section>
<section class="section"><div class="container"><div class="grid grid-3"><div class="card"><div class="card-number">01 · STRAIGHT-TALKING</div><h3>No invented maturity</h3><p>Launch capabilities, integrations and roadmap items are separated clearly.</p></div><div class="card"><div class="card-number">02 · DEALER-FIRST</div><h3>Designed around daily work</h3><p>The platform starts with the sales floor, stock operation and owner’s questions.</p></div><div class="card"><div class="card-number">03 · CONNECTED</div><h3>One ecosystem</h3><p>Specialist valuation, finance and website journeys feed one operating core.</p></div></div></div></section>''' + cta('Help shape the operating system South African dealers actually need.', 'Founding dealers receive a closer product relationship, clear rollout scope and direct influence over workflow priorities.')
write_pages.append(('/about/', shell('About DealershipCore South Africa', 'Learn why DealershipCore is building a connected growth operating system for South African dealerships.', '/about/', about_body)))

# Contact and demo
contact_body = page_hero('Contact', 'Tell us what is breaking between your dealership systems.', 'Share the current setup, the operational problem and what a better result should look like. We will respond with a practical next step—not a generic software pitch.', '/contact/', None, None, ctas=False) + '''
<section class="section surface-section"><div class="container"><div class="grid grid-2" style="align-items:start"><div><div class="eyebrow">Start the conversation</div><h2>Lead flow, stock, website, valuation or reporting?</h2><p class="lead">The fastest way to help is to understand the exact hand-off that is failing today.</p><div class="card"><h3>Good reasons to contact us</h3><div class="check-list"><div class="check">You are comparing DealershipCore with VMG or another DMS.</div><div class="check">Website and marketplace leads are difficult to track.</div><div class="check">You want a dealership-branded valuation tool.</div><div class="check">You need group-level reporting across branches.</div><div class="check">You want to join the founding dealer programme.</div></div></div></div>''' + audit_form() + '''</div></div></section>'''
write_pages.append(('/contact/', shell('Contact DealershipCore', 'Contact DealershipCore about dealership software, lead management, stock workflows, websites, valuation tools and founding dealer access.', '/contact/', contact_body)))

demo_body = page_hero('Founding dealer access', 'Build the first DealershipCore rollout around your dealership.', 'Request a systems audit and product conversation. We will map your current tools, identify the most valuable starting workflow and separate what can launch now from what needs integration or roadmap work.', '/book-demo/', 'What happens next', 'We review the information, schedule a practical working session and prepare a rollout recommendation. No automatic calendar ambush and no hidden claim that every module is finished.', ctas=False) + '''
<section class="section surface-section"><div class="container"><div class="grid grid-2" style="align-items:start"><div><div class="eyebrow">The founding dealer process</div><h2>Start with the system you run today.</h2><div class="check-list"><div class="check"><strong>1. Map:</strong>&nbsp; current DMS, website, lead sources and reporting.</div><div class="check"><strong>2. Diagnose:</strong>&nbsp; find the hand-offs creating delay or blind spots.</div><div class="check"><strong>3. Scope:</strong>&nbsp; identify launch modules, integrations and migration needs.</div><div class="check"><strong>4. Pilot:</strong>&nbsp; implement one high-value workflow with clear success measures.</div><div class="check"><strong>5. Expand:</strong>&nbsp; connect more of the dealership from the same core record.</div></div><div class="note">Founding access is not a promise that every workshop, accounting or mobile-app feature already exists. The scope will state what is live, configurable, integrated or roadmap.</div></div>''' + audit_form() + '''</div></div></section>'''
write_pages.append(('/book-demo/', shell('Request DealershipCore Founding Dealer Access', 'Request founding dealer access, a dealership systems audit and a practical rollout conversa