pe Town</span><span>R840k</span><span>3</span></div><div class="table-row"><span>Bellville</span><span>R620k</span><span>2</span></div><div class="table-row"><span>Somerset West</span><span>R380k</span><span>2</span></div></div></div></div>'''


def faq_block(items):
    return '<div class="faq">' + ''.join(f'<div class="faq-item"><button class="faq-question" type="button" aria-expanded="false"><span>{escape(q)}</span><span>+</span></button><div class="faq-answer"><div><p>{escape(a)}</p></div></div></div>' for q,a in items) + '</div>'


def audit_form(compact=False):
    return '''<form class="form-shell multi-step" data-lead-form>
      <input class="hp" type="text" name="website" tabindex="-1" autocomplete="off" aria-hidden="true">
      <input type="hidden" name="source" value="dealership-systems-audit">
      <div class="step-indicator"><span class="step-dot active"></span><span class="step-dot"></span><span class="step-dot"></span></div>
      <div class="form-step active"><h3>First, tell us about the dealership.</h3><p>One useful detail at a time. No long generic enquiry form.</p><div class="form-grid"><div class="field"><label for="audit-dealership">Dealership name</label><input id="audit-dealership" name="dealership" required placeholder="Your dealership"></div><div class="field"><label for="audit-role">Your role</label><select id="audit-role" name="role" required><option value="">Choose one</option><option>Owner / Dealer principal</option><option>General manager</option><option>Sales manager</option><option>Marketing / CRM</option><option>Other</option></select></div><div class="field"><label for="audit-branches">Number of branches</label><select id="audit-branches" name="branches"><option>1</option><option>2–3</option><option>4–10</option><option>11+</option></select></div><div class="field"><label for="audit-stock">Typical stock size</label><select id="audit-stock" name="stock_size"><option>Under 30 vehicles</option><option>30–75 vehicles</option><option>76–150 vehicles</option><option>150+ vehicles</option></select></div></div><div class="button-row" style="margin-top:22px"><button class="btn btn-primary" type="button" data-next>Continue <span class="arrow">→</span></button></div></div>
      <div class="form-step"><h3>Where is the biggest operational gap?</h3><p>This helps us focus the audit on the part of the dealership that matters most.</p><div class="field"><label for="audit-challenge">Describe the current challenge</label><textarea id="audit-challenge" name="challenge" required placeholder="For example: leads are spread across inboxes, website stock is often outdated, or we cannot see follow-up across the team."></textarea></div><div class="field" style="margin-top:16px"><label for="audit-system">Current software or process</label><input id="audit-system" name="current_system" placeholder="VMG, spreadsheets, another CRM, or a mix"></div><div class="button-row" style="margin-top:22px"><button class="btn btn-secondary" type="button" data-back>Back</button><button class="btn btn-primary" type="button" data-next>Continue <span class="arrow">→</span></button></div></div>
      <div class="form-step"><h3>Where should we send the next step?</h3><div class="form-grid"><div class="field"><label for="audit-name">Your name</label><input id="audit-name" name="name" required autocomplete="name" placeholder="Full name"></div><div class="field"><label for="audit-email">Work email</label><input id="audit-email" name="email" required type="email" autocomplete="email" placeholder="name@dealership.co.za"></div><div class="field full"><label for="audit-phone">Phone / WhatsApp</label><input id="audit-phone" name="phone" autocomplete="tel" placeholder="Optional"></div><label class="checkbox full"><input type="checkbox" name="consent" required><span>I agree that DealershipCore may contact me about this audit and relevant dealership software services. I can opt out at any time.</span></label></div><div class="button-row" style="margin-top:22px"><button class="btn btn-secondary" type="button" data-back>Back</button><button class="btn btn-primary" type="submit">Request my dealership audit <span class="arrow">→</span></button></div><div class="form-status" role="status" aria-live="polite"></div></div>
    </form>'''


def cta(title='Your dealership does not need another disconnected tool.', text='See how DealershipCore can connect lead flow, stock visibility, website activity and owner reporting around one practical operating system.'):
    return f'''<section class="section"><div class="container"><div class="cta-panel reveal"><div class="eyebrow">Founding dealer programme</div><h2>{title}</h2><p class="lead">{text}</p><div class="button-row"><a class="btn btn-primary btn-lg" href="/book-demo/">Request founding dealer access <span class="arrow">→</span></a><a class="btn btn-secondary btn-lg" href="/contact/">Ask a question</a></div></div></div></section>'''

# HOME
home_faq = [
    ('What is DealershipCore?', 'DealershipCore is a dealership growth and operating platform designed to connect stock, websites, vehicle valuation journeys, leads, follow-up, automation and owner reporting.'),
    ('Is DealershipCore a replacement for VMG?', 'It can replace or complement parts of an existing dealership stack depending on the dealership. VMG is an established South African DMS with mature administration, workshop and accounting modules. DealershipCore is initially focused on modern growth workflows, web conversion, lead accountability, valuation funnels and owner visibility.'),
    ('Is the platform already available?', 'DealershipCore is opening a founding dealer programme. Early partners help shape integrations, workflow priorities and rollout requirements.'),
    ('Can it connect to our existing website?', 'Yes, where the website and its integrations allow it. DealershipCore can also support a new connected dealership website when the current site cannot deliver the required experience.'),
    ('Does DealershipCore include vehicle valuation tools?', 'Yes. The ecosystem includes consumer valuation and sell-my-car journeys that can feed structured opportunities into DealershipCore.'),
    ('How will pricing work?', 'Founding dealer pricing is scoped around branch count, stock volume, required modules, integrations and onboarding. The pricing page explains the planned packaging without inventing a one-size-fits-all number.'),
]
home_body = f'''
<section class="hero"><div class="container"><div class="hero-copy"><div class="eyebrow">Built for South African dealerships</div><h1>Run your dealership from <span class="gradient-text">one core system.</span></h1><p class="lead">Connect stock, websites, valuation leads, sales follow-up, automation and owner reporting—so every enquiry has an owner, every vehicle has a clear status and every manager can see what needs attention.</p><div class="button-row"><a class="btn btn-primary btn-lg" href="/book-demo/">Request founding de