 {
        'title': 'Vehicle Valuation and Sell My Car Tools for Dealers',
        'meta': 'Turn vehicle valuation demand into structured acquisition leads connected directly to your dealership sales and buying workflow.',
        'eyebrow': 'Valuation tools',
        'headline': 'Build a repeatable vehicle acquisition channel—not another disconnected form.',
        'intro': 'DealershipCore connects consumer valuation experiences, photo capture, ownership details and buying intent to a dealership workflow built for fast qualification.',
        'pain': 'Many “sell my car” forms collect only a phone number. That creates slow back-and-forth and weak qualification before a buyer can act.',
        'outcome': 'Structured vehicle data, condition information, photos, consent and contact details delivered to the right dealer team with a clear next action.',
        'bullets': ['White-label valuation journeys', 'Vehicle details and condition capture', 'Photo and document collection', 'Trade-in, sell and finance pathways', 'Dealer buying rules and review workflow', 'Lead delivery into DealershipCore'],
        'visual': 'feed',
        'faqs': [('Is the valuation fully automatic?', 'The experience can combine automated guidance with dealership review. The final offer process should match the dealer’s buying policy and available data.'), ('Can the tool use our dealership brand?', 'Yes. White-label journeys can use the dealer’s logo, colours, domain and contact flow.'), ('Where do valuation leads go?', 'They are routed into DealershipCore with vehicle, source and customer context attached.')],
    },
    'automation': {
        'title': 'Dealership Sales and Operations Automation',
        'meta': 'Automate dealership lead routing, reminders, follow-up tasks, status alerts and management reporting without losing human control.',
        'eyebrow': 'Automation',
        'headline': 'Automate the hand-offs that cost your team time and your dealership deals.',
        'intro': 'DealershipCore uses practical dealership rules to create tasks, route enquiries, flag delays and keep the next action visible without turning the sales process into a black box.',
        'pain': 'Most dealership leakage happens between systems and people: a form arrives, nobody owns it, a follow-up date passes or a vehicle changes status without the right person knowing.',
        'outcome': 'A visible automation layer that handles repetitive coordination while keeping managers in control of the customer relationship.',
        'bullets': ['Automatic lead assignment', 'Follow-up and escalation reminders', 'New stock and sold-stock alerts', 'Pipeline ageing and inactivity warnings', 'Daily management summaries', 'Approval controls for sensitive actions'],
        'visual': 'feed',
        'faqs': [('Can automations be changed?', 'Yes. Rules should be configured around the dealership’s real team structure and workflow.'), ('Will it send messages without approval?', 'Approval behaviour depends on the chosen automation level. Sensitive customer communication can remain review-first.'), ('Can it alert a manager when a lead is ignored?', 'Yes. Escalation rules can surface unassigned or overdue leads.')],
    },
    'reporting': {
        'title': 'Dealership Reporting and Owner Dashboards',
        'meta': 'See dealership lead flow, response time, stock activity, pipeline, source performance and branch results in one owner-level dashboard.',
        'eyebrow': 'Reporting',
        'headline': 'See what is happening before month-end reports tell you what already went wrong.',
        'intro': 'DealershipCore is designed to show owners and managers the work, risks and opportunities that need attention today—not only historical totals.',
        'pain': 'Reports lose their value when every department uses different numbers or when the owner receives a spreadsheet days after decisions should have been made.',
        'outcome': 'One operational truth for lead flow, response speed, pipeline, source performance, stock ageing and team activity.',
        'bullets': ['Owner and manager command centre', 'Lead and response-time reporting', 'Pipeline by salesperson and branch', 'Stock ageing and readiness views', 'Campaign and source performance', 'Exportable, date-filtered reports'],
        'visual': 'owner',
        'faqs': [('Can reports show branch performance?', 'Yes. Data can be viewed per branch and consolidated for a dealer group.'), ('Can I compare periods?', 'Yes. Reporting is designed for clear date ranges and comparison periods.'), ('Are the dashboard examples real customer numbers?', 'No. Website visuals are illustrative product examples and are labelled as such.')],
    },
}

SOLUTIONS = {
    'independent-dealers': {
        'title': 'Dealership Software for Independent Dealers in South Africa',
        'meta': 'DealershipCore helps independent dealers manage stock, website leads, follow-up, valuation opportunities and owner reporting from one modern system.',
        'eyebrow': 'Independent dealers',
        'headline': 'Built for the dealer who still has to know what is happening everywhere.',
        'intro': 'Independent dealership owners cannot afford disconnected tools, slow follow-up or reports that arrive too late. DealershipCore gives the owner one practical operating view.',
        'needs': ['A clear view of every new lead', 'Stock and website information that stays aligned', 'Follow-up that does not depend on memory', 'Simple reporting without enterprise complexity'],
        'fit': 'DealershipCore is designed to remove operational blind spots while remaining flexible enough for the way independent dealerships actually work.',
    },
    'dealer-groups': {
        'title': 'Multi-Branch Dealership Software for Dealer Groups',
        'meta': 'Give dealership groups branch-level control, group-level reporting, lead routing, permissions and shared operating standards.',
        'eyebrow': 'Dealer groups',
        'headline': 'One group view without removing the way each branch needs to operate.',
        'intro': 'DealershipCore connects branches through shared reporting, routing standards, permissions and owner oversight while preserving branch accountability.',
        'needs': ['Group and branch reporting', 'Branch-aware lead assignment', 'Shared stock visibility with clear ownership', 'Roles, permissions and audit history'],
        'fit': 'The platform is structured for central visibility and local execution—so head office sees the truth without slowing the people doing the work.',
    },
    'used-car-dealerships': {
        'title': 'Used Car Dealership Software and Lead Management',
        'meta': 'Manage used vehicle stock, valuation leads, recon readiness, website enquiries and sales follow-up in one connected dealership platform.',
        'eyebrow': 'Used car dealerships',
        'headline': 'Used vehicle retail moves quickly. Your systems must move faster.',
        