atures/{slug}/', 'Designed around a complete workflow', 'The page explains the operational problem, the connected mechanism and the owner-level outcome—not only a feature list.')
    body += f'''<section class="section surface-section"><div class="container"><div class="story-row"><div class="story-copy reveal"><div class="eyebrow">Where dealerships lose control</div><h2>{data['pain']}</h2><p class="lead">{data['outcome']}</p><div class="check-list">{''.join(f'<div class="check">{b}</div>' for b in data['bullets'])}</div></div>{visual(data['visual'])}</div></div></section>
<section class="section"><div class="container"><div class="text-center"><div class="eyebrow">What changes</div><h2>One connected operating loop.</h2><p class="lead">Capture the information once, make the next action clear, keep the history visible and show managers where attention is needed.</p></div><div class="grid grid-4" style="margin-top:42px"><div class="card reveal"><div class="card-number">01 · CAPTURE</div><h3>Structured input</h3><p>Record the customer, vehicle, source and intent in a consistent format.</p></div><div class="card reveal delay-1"><div class="card-number">02 · ROUTE</div><h3>Clear ownership</h3><p>Assign the work using dealership rules instead of shared-inbox guesswork.</p></div><div class="card reveal delay-2"><div class="card-number">03 · ACT</div><h3>Visible next step</h3><p>Give the responsible person a deadline, context and practical action.</p></div><div class="card reveal delay-3"><div class="card-number">04 · LEARN</div><h3>Owner visibility</h3><p>Measure where the process moves, slows down or needs improvement.</p></div></div></div></section>
<section class="section surface-section"><div class="narrow text-center"><div class="eyebrow">Questions</div><h2>What dealerships usually ask.</h2>{faq_block(data['faqs'])}</div></section>{cta()}'''
    write_pages.append((f'/features/{slug}/', shell(data['title'], data['meta'], f'/features/{slug}/', body, active='/platform/', faq=data['faqs'])))

# Solution pages
for slug,data in SOLUTIONS.items():
    body = page_hero(data['eyebrow'], data['headline'], data['intro'], f'/solutions/{slug}/', 'A workflow built around your operating model', data['fit'])
    body += f'''<section class="section surface-section"><div class="container"><div class="grid grid-2" style="align-items:center"><div class="reveal"><div class="eyebrow">What this dealership needs</div><h2>Clarity where the daily operation becomes messy.</h2><div class="check-list">{''.join(f'<div class="check">{n}</div>' for n in data['needs'])}</div><p class="lead">{data['fit']}</p></div>{visual('owner' if slug=='dealer-groups' else 'pipeline')}</div></div></section>
<section class="section"><div class="container"><div class="eyebrow">Recommended starting modules</div><h2>Start with the bottleneck. Expand from one connected foundation.</h2><div class="grid grid-3" style="margin-top:38px"><a class="card card-hover feature-card" href="/features/lead-management/"><div class="icon-box">L</div><h3>Lead management</h3><p>One visible process for every source, salesperson and next action.</p><span class="text-link">View module <span class="arrow">→</span></span></a><a class="card card-hover feature-card" href="/features/stock-management/"><div class="icon-box">S</div><h3>Stock visibility</h3><p>Connect operational vehicle status to web readiness and customer interest.</p><span class="text-link">View module <span class="arrow">→</span></span></a><a class="card card-hover feature-card" href="/features/reporting/"><div class="icon-box">R</div><h3>Owner reporting</h3><p>See exceptions and actions before they become month-end explanations.</p><span class="text-link">View module <span class="arrow">→</span></span></a></div></div></section>{cta()}'''
    write_pages.append((f'/solutions/{slug}/', shell(data['title'], data['meta'], f'/solutions/{slug}/', body, active='/solutions/')))

# Ecosystem
eco_faq=[('Why use multiple domains?', 'Each domain can target a distinct search or campaign intention. The content and user journey should be genuinely different, while the operational lead record still flows into DealershipCore.'), ('Will the sites compete with each other?', 'They should not duplicate the same pages. VehicleValuation.co.za should act as the main authority, while other domains target narrower consumer, technical or international intentions.'), ('Can dealers white-label the tools?', 'Yes. Dealer-branded valuation and sell-my-car journeys are a central product direction.')]
eco_body = page_hero('DealershipCore ecosystem', 'Different demand channels. One operating system.', 'The DealershipCore ecosystem uses specialised domains to attract consumer and dealer intent, then connects every meaningful action to one central dealership workflow.', '/ecosystem/', 'Built as a network, not a domain collection', 'Each property has a distinct audience, search purpose and conversion role.') + '''
<section class="section surface-section"><div class="container"><div class="text-center"><div class="eyebrow">South African growth network</div><h2>Every domain has one job.</h2><p class="lead">The strategy avoids duplicate websites. Each property answers a different question and moves the visitor toward a relevant next step.</p></div><div class="grid grid-3" style="margin-top:42px"><div class="card"><div class="tag">Core platform</div><h3>DealershipCore.co.za</h3><p>Main South African SaaS platform for dealers, branches, stock, leads, websites and reporting.</p></div><div class="card"><div class="tag">Consumer authority</div><h3>VehicleValuation.co.za</h3><p>Main public vehicle valuation platform and highest-authority valuation property.</p></div><div class="card"><div class="tag">SEO feeder</div><h3>CarValuation.co.za</h3><p>High-intent educational pages and search journeys feeding the main valuation experience.</p></div><div class="card"><div class="tag">Consumer campaign</div><h3>ValueMyCars.co.za</h3><p>Simple consumer-first campaign experience for valuation and sell-my-car demand.</p></div><div class="card"><div class="tag">Post-valuation finance</div><h3>FinanceYourCars.co.za</h3><p>Finance lead funnel for customers moving from valuation or vehicle discovery into affordability.</p></div><div class="card"><div class="tag">Dealer SEO</div><h3>DealershipSoftware.co.za</h3><p>Dealer education, comparison and high-intent software discovery feeding DealershipCore demos.</p></div><div class="card"><div class="tag">Technical product</div><h3>VehicleValuationEngine.co.za</h3><p>Technical landing pages for valuation technology, API logic and dealership integration.</p></div><div class="card"><div class="tag">International engine</div><h3>VehicleValuationEngine.com</h3><p>International valuation engine positioning for markets outside South Africa.</p></div><div class="card"><div class="tag">White-label tool</div><h3>SellMyCarTool.com</h3><p>International white-label sell-my-car product for dealers