tion with DealershipCore.', '/book-demo/', demo_body)))

# Resources hub
resource_cards=''.join(f'<a class="card card-hover resource-card" href="/resources/{slug}/"><span class="tag">Guide</span><h3>{data["title"]}</h3><p>{data["description"]}</p><span class="text-link">Read guide · {data["read"]} <span class="arrow">→</span></span></a>' for slug,data in ARTICLES.items())
resources_body = page_hero('Dealership resources', 'Useful guidance for dealership owners choosing systems, fixing lead flow and building vehicle acquisition channels.', 'Practical, plain-English resources built around dealership operations—not generic SaaS content written to fill a blog.', '/resources/', 'Authority should be useful', 'Every guide answers a real buyer or operator question and connects to a relevant next action.') + f'<section class="section surface-section"><div class="container"><div class="grid grid-3">{resource_cards}</div></div></section>' + cta()
write_pages.append(('/resources/', shell('Dealership Software and Growth Resources', 'Read practical guides on dealership software, lead response, vehicle valuation funnels, websites and operating workflows.', '/resources/', resources_body, active='/resources/')))

# Articles
for slug,data in ARTICLES.items():
    toc=''.join(f'<a href="#{i}">{title}</a>' for i,(title,_) in enumerate(data['sections'],1))
    sections=''.join(f'<section id="{i}"><h2>{title}</h2>{html}</section>' for i,(title,html) in enumerate(data['sections'],1))
    body=f'''<section class="page-hero"><div class="narrow"><div class="breadcrumbs"><a href="/">Home</a><span>/</span><a href="/resources/">Resources</a><span>/</span><span>Guide</span></div><div class="eyebrow">Dealership guide</div><h1>{data['title']}</h1><p class="lead">{data['description']}</p><div class="resource-meta"><span>Published 1 August 2026</span><span>{data['read']}</span><span>DealershipCore editorial</span></div></div></section><section class="section surface-section"><div class="container article-wrap"><aside class="article-nav"><strong>In this guide</strong>{toc}</aside><article class="prose">{sections}<div class="cta-panel" style="margin-top:54px;padding:36px"><h2 style="font-size:2rem">Turn the guide into a dealership workflow.</h2><p>Request a systems audit and apply the framework to your current lead, stock and website setup.</p><a class="btn btn-primary" href="/book-demo/">Request an audit <span class="arrow">→</span></a></div></article></div></section>'''
    write_pages.append((f'/resources/{slug}/', shell(data['title'], data['meta'], f'/resources/{slug}/', body, active='/resources/', article=True)))

# Privacy and terms
privacy_body = page_hero('Privacy policy', 'How DealershipCore handles website and enquiry information.', 'This policy explains the information collected through DealershipCore.co.za and the choices available to website visitors and dealership contacts.', '/privacy/', None, None, ctas=False) + '''<section class="section surface-section"><div class="narrow prose"><h2>Information we collect</h2><p>We collect information you submit through enquiry, audit and founding-dealer forms, including name, contact details, dealership information, role, current systems and the operational challenge you describe. Technical data may include page, referral, campaign, approximate location and security information supplied by the hosting platform.</p><h2>How we use information</h2><p>We use information to respond to requests, prepare relevant dealership software recommendations, improve the website, prevent abuse, maintain records and communicate about DealershipCore services where permission exists.</p><h2>Sharing and processing</h2><p>Information may be processed by infrastructure, communication and analytics providers necessary to operate the service. We do not sell personal information. Access is limited to people and providers who require it for the stated purpose.</p><h2>POPIA rights</h2><p>South African data subjects may request access, correction or deletion where applicable. Contact DealershipCore through the contact page and provide enough information to identify the relevant record.</p><h2>Retention and security</h2><p>We retain information only as long as reasonably required for the purpose, legal obligations and legitimate business records. Reasonable technical and organisational safeguards are used, but no online system can guarantee absolute security.</p><h2>Updates</h2><p>This policy may change as the product and processing activities develop. The current version is dated 1 August 2026.</p></div></section>'''
write_pages.append(('/privacy/', shell('DealershipCore Privacy Policy', 'Read the DealershipCore privacy policy for website enquiries, dealership audit requests and founding dealer access.', '/privacy/', privacy_body)))
terms_body = page_hero('Website terms', 'Terms for using DealershipCore.co.za.', 'These terms apply to the public website, resources, comparison content and enquiry forms.', '/terms/', None, None, ctas=False) + '''<section class="section surface-section"><div class="narrow prose"><h2>Website information</h2><p>Website content is general product and marketing information. It is not a binding software specification, implementation commitment, financial recommendation or legal advice.</p><h2>Product status</h2><p>DealershipCore is opening a founding dealer programme. Pages distinguish launch focus, illustrative product views and roadmap areas. Final functionality, integrations, pricing and implementation scope are defined in a written proposal or agreement.</p><h2>Comparison content</h2><p>Competitor information is based on publicly available material reviewed on the date stated. Product features and pricing may change. Verify current information directly with the relevant provider.</p><h2>Intellectual property</h2><p>DealershipCore branding, original website copy, software concepts and visual materials are protected by applicable intellectual property law. Third-party names remain the property of their owners.</p><h2>Acceptable use</h2><p>Do not attempt to interfere with the website, submit false information, exploit forms or use content unlawfully.</p><h2>Limitation</h2><p>The website is provided on an as-available basis. To the extent permitted by law, DealershipCore is not liable for decisions made solely from general website information.</p><h2>Current version</h2><p>These website terms are dated 1 August 2026.</p></div></section>'''
write_pages.append(('/terms/', shell('DealershipCore Website Terms', 'Read the terms for using DealershipCore.co.za, its resources, product information and comparison pages.', '/terms/', terms_body)))

# write files
for path,html in write_pages:
    target = ROOT / ('index.html' if path == '/' else path.strip('/') + '/index.html')
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(html, encoding='utf-8')

# 404
(ROOT/'404.html').write_text('''<!doctype html><html lang="en-ZA"><head><meta c