w"><div class="story-copy"><div class="eyebrow">Who should consider DealershipCore</div><h2>Dealers who need growth systems to connect with dealership operations.</h2><div class="check-list"><div class="check">You want valuation and sell-my-car demand to flow into a real dealer workflow.</div><div class="check">Your website generates leads but gives managers weak visibility.</div><div class="check">You need one view of lead ownership, response and next action.</div><div class="check">You want a founding-dealer relationship that can shape the platform.</div></div></div>''' + visual('owner') + '''</div></div></section>
<section class="section"><div class="narrow text-center"><div class="eyebrow">Comparison questions</div><h2>Choose based on the workflow—not a slogan.</h2>''' + faq_block(compare_faq) + '</div></section>' + cta('Do not replace a working system without understanding the real gap.', 'Start with a dealership systems audit. We will map what VMG or your current tools already handle, where the growth workflow breaks and whether DealershipCore should replace, connect or leave those parts alone.')
write_pages.append(('/compare/vmg-alternative/', shell('DealershipCore vs VMG Software: A Fair South African DMS Comparison', 'Compare DealershipCore and VMG Software across dealership administration, workshop, websites, lead management, valuation funnels, automation and reporting.', '/compare/vmg-alternative/', compare_body, active='/compare/', faq=compare_faq)))

# Spreadsheets comparison
spread_body = page_hero('DealershipCore vs spreadsheets', 'A spreadsheet records what someone typed. A dealership operating system controls what happens next.', 'Spreadsheets remain useful for analysis and exports. They become dangerous when lead ownership, stock status and follow-up depend on separate files that cannot enforce a workflow.', '/compare/dealershipcore-vs-spreadsheets/', 'Use spreadsheets where they are strong', 'Exports, scenario planning and ad-hoc analysis are useful. The daily operating record needs permissions, history, automation and accountability.') + '''
<section class="section surface-section"><div class="container"><div class="matrix"><div class="matrix-row matrix-head"><div>Daily requirement</div><div>DealershipCore</div><div>Spreadsheet</div></div><div class="matrix-row"><div>Single current record</div><div class="yes">Controlled record</div><div class="partial">Depends on file discipline</div></div><div class="matrix-row"><div>Lead ownership and deadlines</div><div class="yes">Assigned and visible</div><div class="partial">Manual columns and reminders</div></div><div class="matrix-row"><div>Audit history</div><div class="yes">Record-level activity</div><div class="partial">Version history varies</div></div><div class="matrix-row"><div>Role permissions</div><div class="yes">Purpose-built</div><div class="partial">File or sheet-level controls</div></div><div class="matrix-row"><div>Website and form integration</div><div class="yes">Direct workflow</div><div class="no">Usually manual or connector-based</div></div><div class="matrix-row"><div>Management alerts</div><div class="yes">Rules and exceptions</div><div class="partial">Requires custom setup</div></div></div></div></section>''' + cta()
write_pages.append(('/compare/dealershipcore-vs-spreadsheets/', shell('DealershipCore vs Spreadsheets for Dealership Management', 'Compare dealership operating software with spreadsheets for lead ownership, stock records, follow-up, permissions, automation and reporting.', '/compare/dealershipcore-vs-spreadsheets/', spread_body, active='/compare/')))

# Pricing
price_faq=[('Why are exact subscription prices not published yet?', 'The founding-dealer programme is being scoped around branch count, stock volume, integrations and implementation requirements. Publishing a fake low starting price would be less useful than showing what drives the commercial model.'), ('Will there be setup costs?', 'Implementation may include data preparation, workflow configuration, integrations, training and website work. These are separated from recurring software fees in the proposal.'), ('Can we start with one module?', 'Yes. A staged rollout can start with lead management, valuation funnels, website integration or reporting, then expand.')]
pricing_body = page_hero('Pricing', 'Transparent scope before a false “from” price.', 'DealershipCore pricing is structured around the real dealership footprint: branches, stock volume, users, modules, integrations and onboarding. Founding dealers receive a clear proposal before implementation.', '/pricing/', 'Founding dealer commercial model', 'No invented discount countdowns. No hidden workshop or accounting claim. Every included module and implementation item is documented.') + '''
<section class="section surface-section"><div class="container"><div class="pricing-grid"><div class="price-card"><div class="tag">Start</div><h3>Growth Core</h3><p>For an independent dealership that needs lead accountability and connected website conversion first.</p><div class="price">Scoped<small> / dealership</small></div><div class="price-caption">Based on users, stock and required connections</div><div class="price-list"><div>Lead command centre</div><div>Sales pipeline</div><div>Website form integration</div><div>Response and follow-up reporting</div><div>Onboarding and workflow setup</div></div><a class="btn btn-secondary" href="/book-demo/">Request scope</a></div><div class="price-card featured"><div class="price-badge">Recommended</div><div class="tag">Grow</div><h3>Dealer Growth OS</h3><p>For a dealership that wants stock, valuation funnels, lead flow and owner visibility connected.</p><div class="price">Scoped<small> / dealership</small></div><div class="price-caption">Founding-dealer proposal after systems audit</div><div class="price-list"><div>Everything in Growth Core</div><div>Connected stock view</div><div>Valuation / sell-my-car funnel</div><div>Automation and escalation rules</div><div>Owner command centre</div><div>Priority product feedback channel</div></div><a class="btn btn-primary" href="/book-demo/">Request founding access</a></div><div class="price-card"><div class="tag">Scale</div><h3>Dealer Group</h3><p>For multi-branch operations needing shared standards, permissions and consolidated reporting.</p><div class="price">Custom<small> / group</small></div><div class="price-caption">Branch-aware implementation and integrations</div><div class="price-list"><div>Group and branch workspaces</div><div>Role-based permissions</div><div>Cross-branch routing rules</div><div>Consolidated owner reporting</div><div>Integration and migration planning</div></div><a class="btn btn-secondary" href="/contact/">Discuss group rollout</a></div></div></div></section>
<section class="section"><div class="container"><div class="grid grid-2"><div><div class="eyebrow">What affects price</div><h2>A clear commercial model.</h2><div class="check-list"><div class="check">