import { rmSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { css } from './styles-v4.mjs';
import { features, solutions, ecosystem, resources } from './site-data-v4.mjs';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const PUBLIC = join(ROOT, 'public');
const BASE = 'https://dealershipcore.co.za';
rmSync(PUBLIC, { recursive: true, force: true });
mkdirSync(join(PUBLIC, 'assets'), { recursive: true });

const iconMap = {
  'lead-management':'<path d="M4 5h16v11H8l-4 3V5Z"/><path d="M8 9h8M8 13h5"/>',
  'stock-management':'<path d="M3 15l2-6h14l2 6v4H3v-4Z"/><path d="M6 9l2-4h8l2 4M6 19v2M18 19v2"/><circle cx="7" cy="16" r="1"/><circle cx="17" cy="16" r="1"/>',
  'crm-customers':'<circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2.5-6 6-6s6 2 6 6M17 7h4M19 5v4M16 14h5M16 18h5"/>',
  'marketing-tools':'<path d="M4 13h4l8 5V6l-8 5H4v2Z"/><path d="M8 13l1 6h3M19 9c1 1 1 5 0 6"/>',
  'sales-deals':'<path d="M4 19V9M10 19V5M16 19v-7M22 19H2"/><path d="m4 7 6-4 6 6 5-5"/>',
  'reports-insights':'<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/><path d="M3 6h4M9 2h4M15 9h4"/>',
  'finance-accounting':'<path d="M3 8h18M5 8V6l7-3 7 3v2M5 19h14M7 8v8M12 8v8M17 8v8"/>',
  'task-management':'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="m8 9 1.5 1.5L12 8M14 9h3m-9 6 1.5 1.5L12 14m2 1h3"/>',
};
const icon = slug => `<svg viewBox="0 0 24 24" aria-hidden="true">${iconMap[slug] || '<circle cx="12" cy="12" r="8"/>'}</svg>`;
const mark = `<svg class="brand-mark" viewBox="0 0 48 48" aria-hidden="true"><rect x="3" y="3" width="42" height="42" rx="11" fill="#11151b"/><path d="M14 13h11c8 0 13 4 13 11s-5 11-13 11H14V13Zm8 7v8h4c3 0 5-1 5-4s-2-4-5-4h-4Z" fill="#fff"/><rect x="34" y="13" width="4" height="22" rx="2" fill="#e42b43"/></svg>`;

const navGroups = [
  ['Product', [['Overview','/product/'],['Features','/product/features/'],['Integrations','/product/integrations/'],['Updates','/product/updates/'],['Ecosystem','/ecosystem/']]],
  ['Features', features.map(([slug,title]) => [title, `/features/${slug}/`])],
  ["Who it's for", solutions.map(([slug,title]) => [title, `/solutions/${slug}/`])],
];

function logo(){ return `<a class="brand" href="/" aria-label="DealershipCore home">${mark}<span class="brand-word">DEALERSHIP<span>CORE</span></span></a>`; }
function header(){
  const dropdowns = navGroups.map(([label,links]) => `<div class="nav-item"><button type="button">${label}</button><div class="mega"><div class="mega-title">${label}</div><div class="mega-grid">${links.map(([name,href])=>`<a href="${href}">${name}</a>`).join('')}</div></div></div>`).join('');
  const mobile = [...navGroups.flatMap(([,links])=>links.slice(0,4)), ['Pricing','/pricing/'], ['About','/about/']].map(([name,href])=>`<a href="${href}">${name}</a>`).join('');
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container header-inner">${logo()}<nav class="main-nav" aria-label="Primary navigation">${dropdowns}<a href="/pricing/">Pricing</a><a href="/about/">About</a></nav><div class="header-actions"><a class="login-link" href="/login/">Login</a><a class="button button-primary" href="/book-demo/">Book a demo</a><button class="menu-button" type="button" aria-label="Open navigation" aria-expanded="false"><span></span></button></div></div></header><nav class="mobile-menu" aria-label="Mobile navigation">${mobile}<a href="/book-demo/">Book a demo</a></nav>`;
}
function footer(){ return `<footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-brand">${logo()}<p>One connected operating system for dealership stock, leads, customers, sales workflow, valuation demand and owner reporting.</p></div><div><h4>Product</h4><a href="/product/">Overview</a><a href="/product/features/">Features</a><a href="/product/integrations/">Integrations</a><a href="/product/updates/">Updates</a></div><div><h4>Solutions</h4><a href="/solutions/independent-dealers/">Independent dealers</a><a href="/solutions/dealer-groups/">Dealer groups</a><a href="/solutions/used-car-dealers/">Used-car dealers</a><a href="/solutions/finance-managers/">Finance managers</a></div><div><h4>Resources</h4><a href="/resources/blog/">Blog</a><a href="/resources/help-centre/">Help centre</a><a href="/resources/guides/">Guides</a><a href="/ecosystem/">Ecosystem</a></div><div><h4>Company</h4><a href="/about/">About</a><a href="/contact/">Contact</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a></div></div><div class="footer-bottom"><span>© 2026 DealershipCore. South African dealership software.</span><span>Product interface shown is an illustrative demo workspace.</span></div></div></footer>`; }

const productDemo = () => `<div class="product-shell"><div class="product-bar"><div class="window-dots"><i></i><i></i><i></i></div><strong>DealershipCore Dashboard</strong><span class="demo-label">Demo workspace</span></div><div class="product-layout"><aside class="product-sidebar"><div class="side-brand"><i></i> CORE</div>${['Overview','Leads','Customers','Vehicles','Deals','Tasks','Marketing','Reports','Finance'].map((x,i)=>`<a class="${i===0?'active':''}" href="#">${x}</a>`).join('')}</aside><div class="product-main"><div class="product-head"><div><h3>Good morning</h3><span>Everything that needs your attention today.</span></div><button>Last 30 days</button></div><div class="metric-grid"><div class="metric"><small>New leads</small><strong>—</strong><em>Connect your forms</em></div><div class="metric"><small>Pipeline value</small><strong>—</strong><em>No live data</em></div><div class="metric"><small>Stock online</small><strong>—</strong><em>Connect stock</em></div><div class="metric"><small>Reply needed</small><strong>—</strong><em>All clear</em></div></div><div class="product-lower"><div class="panel"><div class="panel-head"><span>Lead activity</span><span>Demo view</span></div><div class="chart"><svg viewBox="0 0 480 150" preserveAspectRatio="none"><path d="M0 126 C55 118 67 85 112 98 S190 116 231 72 S315 91 352 52 S429 65 480 23" fill="none" stroke="#2c6bea" stroke-width="3"/><path d="M0 126 C55 118 67 85 112 98 S190 116 231 72 S315 91 352 52 S429 65 480 23 L480 150 L0 150Z" fill="rgba(44,107,234,.08)"/></svg></div></div><div class="panel"><div class="panel-head"><span>Needs attention</span><span>Today</span></div>${[['L','Assign new leads'],['S','Complete stock media'],['F','Finance follow-up'],['R','Review ageing stock']].map(([i,t])=>`<div class="task-row"><span class="task-icon">${i}</span><div><strong>${t}</strong><span>Waiting for connected data</span></div><b>→</b></div>`).join('')}</div></div></div></div>`;

function schema(title,desc,path,type='WebPage'){
  return JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'Organization','name':'DealershipCore','url':BASE,'description':'Dealership software and operating system for South African dealerships.'},{'@type':type,'name':title,'description':desc,'url':`${BASE}${path}`} ]});
}
function shell(title,desc,path,body,extra=''){
  return `<!doctype html><html lang="en-ZA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | DealershipCore</title><meta name="description" content="${desc}"><link rel="canonical" href="${BASE}${path}"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="website"><meta property="og:title" content="${title} | DealershipCore"><meta property="og:description" content="${desc}"><meta property="og:url" content="${BASE}${path}"><meta property="og:site_name" content="DealershipCore"><meta name="theme-color" content="#11151b"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/dealershipcore-v4.css"><script type="application/ld+json">${schema(title,desc,path)}</script>${extra}</head><body>${header()}<main id="main">${body}</main>${footer()}<script src="/assets/dealershipcore-v4.js" defer></script></body></html>`;
}

function home(){
  const featureCards = features.slice(0,8).map(([slug,title,short,desc])=>`<article class="feature-card"><div class="feature-icon">${icon(slug)}</div><h3>${title}</h3><p>${short}</p><a href="/features/${slug}/">Learn more →</a></article>`).join('');
  const eco = ecosystem.slice(0,6).map(([domain,purpose,desc,label,url])=>`<article class="ecosystem-card"><span>${label}</span><h3>${domain}</h3><p>${purpose}. ${desc}</p><a href="${url}">Explore →</a></article>`).join('');
  return shell('Dealership management software for South Africa','Run stock, leads, customers, sales workflow, valuation demand and reporting from one connected dealership platform.','/',`
<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">The operating system for modern dealerships</span><h1>Run your dealership.<br>Grow your business.<br><span>Close more deals.</span></h1><p>DealershipCore connects leads, customers, stock, marketing, sales workflow, valuation demand and reporting in one clear platform built for South African dealerships.</p><div class="hero-actions"><a class="button button-primary" href="/book-demo/">Book a demo</a><a class="button button-outline" href="/product/">See how it works</a></div><div class="hero-badges"><div class="hero-badge"><strong>All-in-one platform</strong><span>One system, not scattered tools.</span></div><div class="hero-badge"><strong>Built for dealers</strong><span>Workflows shaped around the motor trade.</span></div><div class="hero-badge"><strong>Secure & reliable</strong><span>Clear permissions and accountability.</span></div><div class="hero-badge"><strong>South African focus</strong><span>Local dealer journeys and support.</span></div></div></div>${productDemo()}</div></section>
<section class="logo-strip"><div class="container"><div class="logo-strip-title">Built for the South African dealership ecosystem</div><div class="logo-row">${['Independent dealers','Dealer groups','Used-car dealers','New-car dealers','F&I teams','Marketing teams'].map(x=>`<div class="logo-placeholder">${x}</div>`).join('')}</div></div></section>
<section class="section section-soft"><div class="container"><div class="section-head"><span class="section-kicker">Everything in one place</span><h2>One platform for every part of your dealership.</h2><p>Start with the workflows you need now and expand as your dealership grows.</p></div><div class="feature-grid">${featureCards}</div></div></section>
<section class="section section-dark"><div class="container"><div class="section-head"><span class="section-kicker">Built for results</span><h2>From first enquiry to long-term customer value.</h2><p>DealershipCore connects the work your team already does into one accountable operating flow.</p></div><div class="outcome-grid"><div class="outcome"><span>Attract</span><strong>Get qualified demand</strong><p>Valuation tools, websites, campaigns and SEO.</p></div><div class="outcome"><span>Engage</span><strong>Nurture every lead</strong><p>Lead capture, CRM, tasks and automation.</p></div><div class="outcome"><span>Sell</span><strong>Close more deals</strong><p>Stock, quotes, finance and documents.</p></div><div class="outcome"><span>Serve</span><strong>Keep customers connected</strong><p>After-sales, reminders and support history.</p></div><div class="outcome"><span>Grow</span><strong>See what drives performance</strong><p>Reports, source attribution and owner insights.</p></div></div></div></section>
<section class="section"><div class="container split"><div><span class="section-kicker">Connected dealership growth</span><h2>Your public tools should feed your sales floor.</h2><p>Vehicle valuation, sell-my-car and finance journeys should not stop in a shared inbox. DealershipCore routes structured opportunities into one visible workflow.</p><div class="hero-actions"><a class="button button-red" href="/ecosystem/">Explore the ecosystem</a><a class="button button-outline" href="/product/integrations/">View integrations</a></div></div><div class="check-list"><div class="check-item"><b>1</b><div><strong>Capture</strong><span>Collect structured vehicle, finance and customer intent.</span></div></div><div class="check-item"><b>2</b><div><strong>Route</strong><span>Assign each opportunity by branch, source, stock or team.</span></div></div><div class="check-item"><b>3</b><div><strong>Act</strong><span>Track response, next action and outcome in one pipeline.</span></div></div></div></div></section>
<section class="section section-soft"><div class="container"><div class="section-head"><span class="section-kicker">The DealershipCore ecosystem</span><h2>One parent platform. Multiple focused growth channels.</h2><p>Every domain has a clear role, while DealershipCore remains the system that manages the opportunity.</p></div><div class="ecosystem-grid">${eco}</div><div style="text-align:center;margin-top:28px"><a class="button button-primary" href="/ecosystem/">View all ecosystem products</a></div></div></section>
<section class="section"><div class="container"><div class="section-head"><span class="section-kicker">Built to grow with you</span><h2>A clear path from first setup to multi-branch operations.</h2><p>Choose the implementation scope that matches your dealership today.</p></div><div class="plan-grid"><article class="plan"><span class="plan-tag">Starter</span><h3>Core lead operations</h3><p>For dealerships replacing shared inboxes and spreadsheets.</p><ul><li>Lead inbox and pipeline</li><li>Customer records</li><li>Tasks and follow-up</li><li>Website form routing</li></ul><a class="button button-outline" href="/pricing/">View plan</a></article><article class="plan featured"><span class="plan-tag">Growth</span><h3>Connected dealership growth</h3><p>For dealerships connecting stock, valuation demand and reporting.</p><ul><li>Everything in Starter</li><li>Stock workflows</li><li>Valuation funnels</li><li>Manager reporting</li></ul><a class="button button-red" href="/book-demo/">Book a demo</a></article><article class="plan"><span class="plan-tag">Enterprise</span><h3>Dealer groups</h3><p>For multi-branch teams needing consolidated control.</p><ul><li>Multi-branch views</li><li>Permissions and routing</li><li>Custom integrations</li><li>Group reporting</li></ul><a class="button button-outline" href="/contact/">Talk to sales</a></article></div></div></section>
<section class="cta"><div class="container cta-grid"><div><h2>Ready to run your dealership from one core system?</h2><p>See how DealershipCore can connect your stock, leads, valuation demand and reporting.</p></div><div class="cta-actions"><a class="button button-red" href="/book-demo/">Book a demo</a><a class="button button-dark-outline" href="/contact/">Talk to sales</a></div></div></section>`);
}

function pageHero(kicker,title,intro,panelTitle='Built for dealership operations'){
  return `<section class="page-hero"><div class="container page-grid"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${intro}</p><div class="hero-actions"><a class="button button-primary" href="/book-demo/">Book a demo</a><a class="button button-outline" href="/contact/">Talk to us</a></div></div><aside class="page-panel"><span>DealershipCore</span><strong>${panelTitle}</strong><p>Connected records, clear ownership, visible next actions and reporting designed around real dealership workflows.</p></aside></div></section>`;
}
function genericPage(title,desc,path,kicker='DealershipCore'){
  return shell(title,desc,path,`${pageHero(kicker,title,desc)}<section class="section"><div class="container content-grid"><aside class="side-nav"><a href="/product/">Product overview</a><a href="/product/features/">All features</a><a href="/ecosystem/">Ecosystem</a><a href="/pricing/">Pricing</a><a href="/book-demo/">Book a demo</a></aside><article class="article"><section><h2>Built around dealership work.</h2><p>${desc}</p><p>DealershipCore connects the relevant people, vehicles, customers, tasks and commercial context so the next action remains clear.</p></section><section><h2>What this gives your team</h2><div class="check-list"><div class="check-item"><b>✓</b><div><strong>Clear ownership</strong><span>Every record has a responsible person and a visible next action.</span></div></div><div class="check-item"><b>✓</b><div><strong>Connected information</strong><span>Lead, customer, stock and deal context stay linked instead of scattered.</span></div></div><div class="check-item"><b>✓</b><div><strong>Owner visibility</strong><span>Managers can see attention areas, progress and outcomes without chasing updates.</span></div></div></div></section><section><div class="callout"><strong>Founding dealer programme</strong><p>Early dealerships can help shape workflow priorities and implementation standards.</p></div></section></article></div></section><section class="cta"><div class="container cta-grid"><div><h2>See ${title.toLowerCase()} in DealershipCore.</h2><p>Book a practical walkthrough based on your dealership.</p></div><div class="cta-actions"><a class="button button-red" href="/book-demo/">Book a demo</a></div></div></section>`);
}

function featurePage(item){ const [slug,title,short,desc]=item; return shell(title,`${short} ${desc}`,`/features/${slug}/`,`${pageHero('Feature',title,short,title)}<section class="section"><div class="container split"><div><span class="section-kicker">The problem</span><h2>${short}</h2><p>${desc}</p><p>DealershipCore makes the workflow visible without adding unnecessary complexity to the sales floor.</p></div><div class="feature-card" style="min-height:360px"><div class="feature-icon">${icon(slug)}</div><h3>${title} workflow</h3><p>Connected records, assignment, status, next actions, activity history and reporting context.</p><div class="check-list" style="margin-top:20px"><div class="check-item"><b>1</b><div><strong>Capture the work</strong><span>Bring the relevant details into one record.</span></div></div><div class="check-item"><b>2</b><div><strong>Assign responsibility</strong><span>Make ownership and deadlines visible.</span></div></div><div class="check-item"><b>3</b><div><strong>Measure outcomes</strong><span>Connect activity to dealership results.</span></div></div></div></div></div></section><section class="cta"><div class="container cta-grid"><div><h2>Put ${title.toLowerCase()} into one dealership workflow.</h2><p>See the product with your dealership process in mind.</p></div><div class="cta-actions"><a class="button button-red" href="/book-demo/">Book a demo</a></div></div></section>`); }
function solutionPage(item){ const [slug,title,desc]=item; return genericPage(title,desc,`/solutions/${slug}/`,'Who it is for'); }

function ecosystemPage(){ return shell('DealershipCore ecosystem','See how every dealership, valuation, finance and white-label domain connects into the DealershipCore operating platform.','/ecosystem/',`${pageHero('Connected product ecosystem','One parent platform. Multiple focused growth channels.','Each domain attracts a different audience or intent. DealershipCore remains the operating layer that manages leads, customers, stock, follow-up and reporting.','DealershipCore is the core system')}<section class="section section-soft"><div class="container"><div class="section-head"><span class="section-kicker">All ecosystem domains</span><h2>Every domain has a clear job.</h2><p>Focused websites can rank, convert and serve different markets without becoming disconnected businesses.</p></div><div class="ecosystem-grid">${ecosystem.map(([d,p,desc,label,url])=>`<article class="ecosystem-card"><span>${label}</span><h3>${d}</h3><p>${p}. ${desc}</p><a href="${url}">Visit product →</a></article>`).join('')}</div></div></section><section class="section"><div class="container split"><div><span class="section-kicker">How the system works</span><h2>Demand enters through focused channels. Operations stay central.</h2><p>Valuation, finance, software education and international white-label products can all feed structured opportunities into DealershipCore.</p></div><div class="check-list"><div class="check-item"><b>A</b><div><strong>Attract</strong><span>SEO, campaigns, valuation and finance tools create demand.</span></div></div><div class="check-item"><b>E</b><div><strong>Engage</strong><span>DealershipCore captures, routes and nurtures each opportunity.</span></div></div><div class="check-item"><b>G</b><div><strong>Grow</strong><span>Owners see source performance, pipeline and operational outcomes.</span></div></div></div></div></section>`); }
function pricingPage(){ return shell('Pricing','Flexible DealershipCore implementation plans for independent dealerships and dealer groups.','/pricing/',`${pageHero('Pricing','Choose the right DealershipCore starting point.','Pricing is scoped around dealership size, branches, modules, integrations and implementation needs.','Clear scope before commitment')}<section class="section"><div class="container"><div class="plan-grid"><article class="plan"><span class="plan-tag">Starter</span><h3>Core operations</h3><p>Lead, customer and task management for a single dealership.</p><ul><li>Lead inbox and pipeline</li><li>Customer records</li><li>Tasks and reminders</li><li>Standard onboarding</li></ul><a class="button button-outline" href="/book-demo/">Request pricing</a></article><article class="plan featured"><span class="plan-tag">Growth</span><h3>Connected growth</h3><p>Stock, valuation journeys, marketing attribution and manager reporting.</p><ul><li>Everything in Starter</li><li>Stock workflows</li><li>Valuation funnels</li><li>Reporting and automation</li></ul><a class="button button-red" href="/book-demo/">Book a demo</a></article><article class="plan"><span class="plan-tag">Enterprise</span><h3>Dealer groups</h3><p>Multi-branch operations, permissions and custom integration scope.</p><ul><li>Multi-branch control</li><li>Advanced routing</li><li>Custom integrations</li><li>Group reporting</li></ul><a class="button button-outline" href="/contact/">Talk to sales</a></article></div></div></section>`); }
function formPage(type){ const isDemo=type==='demo'; const title=isDemo?'Book a DealershipCore demo':'Contact DealershipCore'; const desc=isDemo?'Tell us about your dealership and the workflow you want to improve.':'Talk to us about dealership software, valuation tools, integrations or the wider ecosystem.'; return shell(title,desc,isDemo?'/book-demo/':'/contact/',`<section class="section section-soft"><div class="container form-wrap"><div><span class="eyebrow">${isDemo?'Book a demo':'Contact'}</span><h1 style="font-size:58px;letter-spacing:-3px;margin:20px 0 0">${title}</h1><p style="color:var(--muted);line-height:1.7">${desc}</p><div class="check-list" style="margin-top:28px"><div class="check-item"><b>1</b><div><strong>Tell us about the dealership</strong><span>Branches, stock size and current process.</span></div></div><div class="check-item"><b>2</b><div><strong>Identify the biggest gap</strong><span>Leads, stock, reporting, website or valuation demand.</span></div></div><div class="check-item"><b>3</b><div><strong>Plan the right next step</strong><span>A practical product walkthrough or implementation discussion.</span></div></div></div></div><form class="lead-form" data-lead-form><input type="text" name="website" tabindex="-1" autocomplete="off" style="position:absolute;left:-9999px"><div class="form-row"><div><label for="name">Your name</label><input id="name" name="name" required></div><div><label for="email">Work email</label><input id="email" type="email" name="email" required></div></div><div class="form-row"><div><label for="phone">Phone</label><input id="phone" name="phone"></div><div><label for="dealership">Dealership</label><input id="dealership" name="dealership" required></div></div><div class="form-row"><div><label for="role">Your role</label><select id="role" name="role"><option>Dealer principal / owner</option><option>General manager</option><option>Sales manager</option><option>Marketing manager</option><option>Finance manager</option><option>Other</option></select></div><div><label for="branches">Branches</label><select id="branches" name="branches"><option>1</option><option>2–3</option><option>4–10</option><option>10+</option></select></div></div><label for="challenge">What should DealershipCore help improve?</label><textarea id="challenge" name="challenge"></textarea><label style="display:flex;gap:9px;align-items:flex-start;font-weight:600"><input type="checkbox" name="consent" value="on" required style="width:auto;margin-top:2px">You may contact me about this request.</label><button class="button button-red" type="submit">${isDemo?'Request demo':'Send enquiry'}</button><div class="form-status" aria-live="polite"></div></form></div></section>`); }
function loginPage(){ return shell('Login','DealershipCore workspace login.','/login/',`<section class="section section-soft"><div class="container"><div class="lead-form login-panel"><span class="section-kicker">DealershipCore workspace</span><h1 style="font-size:40px;letter-spacing:-2px">Login</h1><p style="color:var(--muted)">The DealershipCore customer workspace is opening with the founding dealer programme.</p><label>Email</label><input type="email" placeholder="you@dealership.co.za"><label>Password</label><input type="password" placeholder="Password"><button class="button button-primary" style="width:100%">Login</button><p style="font-size:11px;color:#7c858f">No active account yet? <a href="/book-demo/" style="color:var(--red);font-weight:800">Request access</a>.</p></div></div></section>`); }

const pages = new Map();
pages.set('/', home());
pages.set('/product/', genericPage('Product overview','One connected platform for dealership stock, leads, customers, sales workflow and reporting.','/product/','Product'));
pages.set('/product/features/', genericPage('DealershipCore features','Explore the complete DealershipCore feature set for modern dealerships.','/product/features/','Product'));
pages.set('/product/integrations/', genericPage('Integrations','Connect dealership websites, valuation journeys, finance funnels and external systems.','/product/integrations/','Product'));
pages.set('/product/updates/', genericPage('Product updates','Follow DealershipCore platform releases, improvements and roadmap progress.','/product/updates/','Product'));
for (const item of features) pages.set(`/features/${item[0]}/`, featurePage(item));
for (const item of solutions) pages.set(`/solutions/${item[0]}/`, solutionPage(item));
pages.set('/ecosystem/', ecosystemPage());
pages.set('/pricing/', pricingPage());
pages.set('/pricing/compare/', genericPage('Compare plans','Compare DealershipCore implementation scopes and product capabilities.','/pricing/compare/','Pricing'));
pages.set('/pricing/faq/', genericPage('Pricing FAQ','Answers about DealershipCore pricing, onboarding and implementation scope.','/pricing/faq/','Pricing'));
pages.set('/resources/', genericPage('Resources','Dealership software, growth, valuation and operational resources.','/resources/','Resources'));
for (const [slug,title,desc] of resources) pages.set(`/resources/${slug}/`, genericPage(title,desc,`/resources/${slug}/`,'Resources'));
pages.set('/about/', genericPage('About DealershipCore','Why DealershipCore exists and the dealership problems it is designed to solve.','/about/','Company'));
pages.set('/about/mission/', genericPage('Our mission','Build a clearer operating system for modern dealerships and dealer groups.','/about/mission/','Company'));
pages.set('/about/team/', genericPage('Our team','The product, dealership and technology thinking behind DealershipCore.','/about/team/','Company'));
pages.set('/about/partners/', genericPage('Partners','Integration and channel partnerships across the dealership ecosystem.','/about/partners/','Company'));
pages.set('/about/careers/', genericPage('Careers','Help build the operating layer for the next generation of dealerships.','/about/careers/','Company'));
pages.set('/contact/', formPage('contact'));
pages.set('/book-demo/', formPage('demo'));
pages.set('/login/', loginPage());
pages.set('/privacy/', genericPage('Privacy policy','How DealershipCore handles website enquiries and product information.','/privacy/','Legal'));
pages.set('/terms/', genericPage('Website terms','Terms governing use of the DealershipCore website.','/terms/','Legal'));

for (const [path,html] of pages) {
  const dir = path==='/' ? PUBLIC : join(PUBLIC,path);
  mkdirSync(dir,{recursive:true});
  writeFileSync(join(dir,'index.html'),html);
}
writeFileSync(join(PUBLIC,'404.html'),`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/dealershipcore-v4.css"><title>Page not found | DealershipCore</title></head><body><main class="section"><div class="container" style="text-align:center"><span class="eyebrow">404</span><h1 style="font-size:58px">Page not found.</h1><p>The page may have moved.</p><a class="button button-primary" href="/">Return home</a></div></main></body></html>`);
writeFileSync(join(PUBLIC,'assets','dealershipcore-v4.css'),css);
writeFileSync(join(PUBLIC,'assets','dealershipcore-v4.js'),`document.addEventListener('DOMContentLoaded',()=>{const m=document.querySelector('.menu-button'),n=document.querySelector('.mobile-menu');m?.addEventListener('click',()=>{const open=n.classList.toggle('open');m.setAttribute('aria-expanded',String(open))});document.querySelectorAll('[data-lead-form]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('.form-status');const button=form.querySelector('button[type=submit]');status.textContent='Sending…';button.disabled=true;const data=Object.fromEntries(new FormData(form));data.page=location.pathname;data.referrer=document.referrer;data.source='dealershipcore-website';try{const r=await fetch('/api/leads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw new Error(result.error||'Could not send request.');status.textContent=result.message||'Thanks — your request has been received.';form.reset()}catch(err){status.textContent=err.message}finally{button.disabled=false}}))});`);
writeFileSync(join(PUBLIC,'favicon.svg'),mark.replace('class="brand-mark" ','').replace('<svg','<svg xmlns="http://www.w3.org/2000/svg"'));
writeFileSync(join(PUBLIC,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${BASE}/sitemap.xml\n`);
writeFileSync(join(PUBLIC,'llms.txt'),`# DealershipCore\n\nDealershipCore is the parent dealership operating platform for stock, leads, customers, valuation demand, finance journeys and reporting.\n\nCore website: ${BASE}\nEcosystem: ${BASE}/ecosystem/\nProduct: ${BASE}/product/\nPricing: ${BASE}/pricing/\n`);
const urls=[...pages.keys()].map(path=>`<url><loc>${BASE}${path}</loc><lastmod>2026-08-02</lastmod></url>`).join('');
writeFileSync(join(PUBLIC,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls}</urlset>`);
console.log(`Generated ${pages.size} pages.`);
