export const css = String.raw`
:root{
  --ink:#101318;
  --muted:#626a75;
  --line:#e2e5e9;
  --soft:#f6f7f8;
  --surface:#fff;
  --dark:#0e1218;
  --dark-2:#151b24;
  --red:#e42b43;
  --red-dark:#bd1f34;
  --blue:#2c6bea;
  --green:#1f9d63;
  --shadow:0 24px 70px rgba(16,24,40,.11);
  --radius:14px;
}
*{box-sizing:border-box}
html{scroll-behavior:smooth;scroll-padding-top:84px}
body{margin:0;background:#fff;color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif;-webkit-font-smoothing:antialiased}
a{color:inherit;text-decoration:none}
button,input,select,textarea{font:inherit}
img,svg{display:block;max-width:100%}
.container{width:min(1240px,calc(100% - 48px));margin:0 auto}
.skip-link{position:fixed;left:16px;top:-80px;z-index:1000;padding:12px 16px;background:#fff;border:1px solid var(--line);transition:top .2s}.skip-link:focus{top:16px}
.site-header{position:sticky;top:0;z-index:100;height:78px;border-bottom:1px solid var(--line);background:rgba(255,255,255,.96);backdrop-filter:blur(16px)}
.header-inner{height:78px;display:flex;align-items:center;justify-content:space-between;gap:26px}
.brand{display:flex;align-items:center;gap:11px;min-width:max-content}
.brand-mark{width:36px;height:36px}
.brand-word{font-size:15px;font-weight:900;letter-spacing:-.03em}.brand-word span{color:var(--red)}
.main-nav{display:flex;align-items:center;gap:27px;font-size:13px;font-weight:700;color:#2b3139}
.main-nav>a,.nav-item>button{min-height:44px;display:flex;align-items:center;border:0;background:transparent;color:inherit;font-weight:700;cursor:pointer}
.nav-item{position:relative}
.nav-item>button:after{content:"";width:7px;height:7px;margin-left:7px;border-right:1.5px solid currentColor;border-bottom:1.5px solid currentColor;transform:rotate(45deg) translateY(-2px)}
.mega{visibility:hidden;opacity:0;pointer-events:none;position:absolute;top:54px;left:50%;width:430px;transform:translate(-50%,8px);padding:18px;border:1px solid var(--line);border-radius:12px;background:#fff;box-shadow:var(--shadow);transition:.16s}
.nav-item:hover .mega,.nav-item:focus-within .mega{visibility:visible;opacity:1;pointer-events:auto;transform:translate(-50%,0)}
.mega-title{padding:4px 8px 11px;color:#7b838f;font-size:10px;font-weight:900;letter-spacing:.13em;text-transform:uppercase}
.mega-grid{display:grid;grid-template-columns:1fr 1fr;gap:3px}
.mega a{padding:11px 10px;border-radius:8px;font-size:12px}.mega a:hover{background:#f5f6f7}
.header-actions{display:flex;align-items:center;gap:12px}.login-link{font-size:13px;font-weight:750}
.button{display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:0 19px;border:1px solid transparent;border-radius:9px;font-size:13px;font-weight:850;cursor:pointer;transition:transform .15s ease,background .15s ease,box-shadow .15s ease}
.button:hover{transform:translateY(-1px)}.button-primary{background:var(--dark);color:#fff}.button-primary:hover{background:#1b222d}.button-red{background:var(--red);color:#fff;box-shadow:0 12px 28px rgba(228,43,67,.2)}.button-red:hover{background:var(--red-dark)}.button-outline{border-color:#cfd4da;background:#fff}.button-light{background:#fff;color:#11151b}.button-dark-outline{border-color:#49515d;color:#fff;background:transparent}
.menu-button{display:none;width:44px;height:44px;border:0;border-radius:8px;background:#f1f3f5}.menu-button span,.menu-button:before,.menu-button:after{content:"";display:block;width:20px;height:2px;margin:4px auto;background:#151a21}
.mobile-menu{display:none;padding:18px 24px;border-bottom:1px solid var(--line);background:#fff}.mobile-menu.open{display:grid;gap:4px}.mobile-menu a{padding:12px 0;border-bottom:1px solid #eff1f3;font-size:14px}
.hero{padding:76px 0 82px;background:#fff;border-bottom:1px solid var(--line)}
.hero-grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:64px;align-items:center}
.eyebrow{display:inline-flex;align-items:center;gap:8px;padding:8px 11px;border:1px solid #d8dce1;border-radius:999px;background:#fafafa;color:#3d444e;font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.eyebrow:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--red)}
.hero h1{max-width:610px;margin:20px 0 0;font-size:clamp(48px,5.5vw,76px);line-height:.98;letter-spacing:-4.3px}.hero h1 span{color:var(--red)}
.hero p{max-width:610px;margin:22px 0 0;color:var(--muted);font-size:17px;line-height:1.7}
.hero-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:29px}.hero-badges{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:32px}.hero-badge{padding-top:12px;border-top:1px solid var(--line)}.hero-badge strong{display:block;font-size:11px}.hero-badge span{display:block;margin-top:4px;color:#7a828d;font-size:10px;line-height:1.4}
.product-shell{overflow:hidden;border:1px solid #cfd4da;border-radius:16px;background:#fff;box-shadow:0 28px 70px rgba(14,20,28,.14)}
.product-bar{height:48px;display:flex;align-items:center;justify-content:space-between;padding:0 15px;border-bottom:1px solid var(--line);background:#fff;font-size:11px}.window-dots{display:flex;gap:5px}.window-dots i{width:8px;height:8px;border-radius:50%;background:#d8dce1}.window-dots i:first-child{background:#ef6b67}.window-dots i:nth-child(2){background:#f0b94d}.window-dots i:nth-child(3){background:#43bd6f}.demo-label{padding:6px 9px;border-radius:999px;background:#f4f5f6;color:#69717b;font-weight:850}
.product-layout{display:grid;grid-template-columns:132px 1fr;min-height:440px}.product-sidebar{padding:18px 11px;background:#11151b}.side-brand{display:flex;align-items:center;gap:8px;padding:0 8px 17px;color:#fff;font-size:10px;font-weight:900}.side-brand i{width:23px;height:23px;border-radius:6px;background:var(--red)}.product-sidebar a{display:block;margin:4px 0;padding:9px 10px;border-radius:7px;color:#8f99a6;font-size:9px}.product-sidebar a.active{background:#252b34;color:#fff}.product-main{padding:19px;background:#f5f6f8}.product-head{display:flex;align-items:center;justify-content:space-between}.product-head h3{margin:0;font-size:18px}.product-head span{display:block;margin-top:4px;color:#77808c;font-size:9px}.product-head button{padding:7px 10px;border:1px solid #d8dce1;border-radius:7px;background:#fff;font-size:9px}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:16px}.metric{padding:12px;border:1px solid #dde1e6;border-radius:8px;background:#fff}.metric small{color:#747d89;font-size:8px}.metric strong{display:block;margin-top:8px;font-size:18px}.metric em{display:block;margin-top:4px;color:var(--green);font-size:8px;font-style:normal}.product-lower{display:grid;grid-template-columns:1.45fr .85fr;gap:10px;margin-top:10px}.panel{padding:13px;border:1px solid #dde1e6;border-radius:8px;background:#fff}.panel-head{display:flex;justify-content:space-between;color:#717a85;font-size:8px}.chart{height:145px;margin-top:10px}.chart svg{width:100%;height:100%}.task-row{display:grid;grid-template-columns:22px 1fr auto;gap:8px;align-items:center;padding:10px 0;border-top:1px solid #edf0f2}.task-row:first-of-type{margin-top:8px}.task-icon{display:grid;place-items:center;width:22px;height:22px;border-radius:6px;background:#fbeaec;color:var(--red);font-size:8px;font-weight:900}.task-row strong{display:block;font-size:8px}.task-row span{display:block;margin-top:2px;color:#8a929d;font-size:7px}.task-row b{font-size:8px;color:#3e4650}
.logo-strip{padding:27px 0;border-bottom:1px solid var(--line);background:#fafafa}.logo-strip-title{text-align:center;color:#7b838d;font-size:9px;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.logo-row{display:grid;grid-template-columns:repeat(6,1fr);gap:22px;align-items:center;margin-top:20px}.logo-placeholder{display:flex;align-items:center;justify-content:center;gap:7px;color:#646d78;font-size:10px;font-weight:850}.logo-placeholder:before{content:"";width:16px;height:16px;border:4px solid #1d232b;border-right-color:transparent;border-radius:50%}
.section{padding:96px 0}.section-soft{background:#f6f7f8}.section-dark{background:var(--dark);color:#fff}.section-head{max-width:780px;margin:0 auto 40px;text-align:center}.section-kicker{color:var(--red);font-size:10px;font-weight:900;letter-spacing:.13em;text-transform:uppercase}.section-head h2{margin:13px 0 0;font-size:clamp(38px,4.6vw,58px);line-height:1.03;letter-spacing:-3px}.section-head p{margin:17px auto 0;color:var(--muted);font-size:16px;line-height:1.65}.section-dark .section-head p{color:#aab3bf}
.feature-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.feature-card{min-height:240px;padding:24px;border:1px solid var(--line);border-radius:12px;background:#fff;transition:.18s}.feature-card:hover{transform:translateY(-4px);box-shadow:0 18px 44px rgba(16,24,40,.09)}.feature-icon{display:grid;place-items:center;width:44px;height:44px;border:1px solid #d8dce1;border-radius:10px;background:#fafafa}.feature-icon svg{width:22px;height:22px;stroke:#20262e;fill:none;stroke-width:1.8}.feature-card h3{margin:20px 0 0;font-size:17px}.feature-card p{margin:10px 0 0;color:var(--muted);font-size:13px;line-height:1.55}.feature-card a{display:inline-flex;margin-top:18px;color:var(--red);font-size:12px;font-weight:850}
.outcome-grid{display:grid;grid-template-columns:repeat(5,1fr);margin-top:45px;border:1px solid #303843}.outcome{padding:26px;border-right:1px solid #303843}.outcome:last-child{border-right:0}.outcome span{color:#f26b7c;font-size:9px;font-weight:900;letter-spacing:.11em;text-transform:uppercase}.outcome strong{display:block;margin-top:13px;font-size:17px;line-height:1.4}.outcome p{margin:8px 0 0;color:#aeb7c3;font-size:11px;line-height:1.5}
.split{display:grid;grid-template-columns:1fr 1fr;gap:70px;align-items:center}.split h2{margin:13px 0 0;font-size:clamp(38px,4.6vw,58px);line-height:1.03;letter-spacing:-3px}.split p{color:var(--muted);line-height:1.7}.check-list{display:grid;gap:1px;border:1px solid var(--line);background:var(--line)}.check-item{display:grid;grid-template-columns:34px 1fr;gap:13px;padding:19px;background:#fff}.check-item b{display:grid;place-items:center;width:32px;height:32px;border-radius:8px;background:#fbeaec;color:var(--red)}.check-item strong{display:block}.check-item span{display:block;margin-top:4px;color:#737c87;font-size:12px;line-height:1.5}
.ecosystem-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.ecosystem-card{padding:22px;border:1px solid var(--line);border-radius:12px;background:#fff}.ecosystem-card:nth-child(3n+1){background:#fafafa}.ecosystem-card span{color:var(--red);font-size:9px;font-weight:900;letter-spacing:.11em;text-transform:uppercase}.ecosystem-card h3{margin:13px 0 0;font-size:18px}.ecosystem-card p{margin:8px 0 0;color:var(--muted);font-size:12px;line-height:1.55}.ecosystem-card a{display:inline-flex;margin-top:15px;font-size:11px;font-weight:850}
.plan-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.plan{padding:28px;border:1px solid var(--line);border-radius:12px;background:#fff}.plan.featured{border-color:var(--red);box-shadow:0 20px 60px rgba(228,43,67,.12)}.plan-tag{display:inline-flex;padding:6px 8px;border-radius:999px;background:#fbeaec;color:var(--red);font-size:9px;font-weight:900}.plan h3{margin:18px 0 0}.plan p{color:var(--muted);font-size:13px;line-height:1.6}.plan ul{padding-left:18px;color:#565e68;font-size:12px;line-height:2}.plan .button{width:100%;margin-top:16px}
.cta{padding:72px 0;background:var(--dark);color:#fff}.cta-grid{display:grid;grid-template-columns:1fr auto;gap:40px;align-items:center}.cta h2{margin:0;font-size:clamp(34px,4.3vw,54px);letter-spacing:-2.7px}.cta p{margin:13px 0 0;color:#aeb7c3}.cta-actions{display:flex;gap:12px}
.page-hero{padding:86px 0;background:#f7f8f9;border-bottom:1px solid var(--line)}.page-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:60px;align-items:center}.page-hero h1{margin:17px 0 0;font-size:clamp(44px,5vw,68px);line-height:1;letter-spacing:-3.7px}.page-hero p{margin:18px 0 0;color:var(--muted);font-size:17px;line-height:1.7}.page-panel{padding:27px;border:1px solid var(--line);border-radius:12px;background:#fff;box-shadow:var(--shadow)}.page-panel span{color:var(--red);font-size:9px;font-weight:900;text-transform:uppercase}.page-panel strong{display:block;margin-top:12px;font-size:23px}.page-panel p{font-size:13px}.content-grid{display:grid;grid-template-columns:260px 1fr;gap:60px}.side-nav{position:sticky;top:110px;align-self:start}.side-nav a{display:block;padding:10px 0;border-bottom:1px solid var(--line);color:#68717d;font-size:12px}.article h2{margin-top:0;font-size:38px;letter-spacing:-2px}.article p{color:var(--muted);line-height:1.75}.article section{padding-bottom:42px}.callout{padding:22px;border-left:3px solid var(--red);background:#fbf3f4}.form-wrap{display:grid;grid-template-columns:.8fr 1.2fr;gap:60px}.lead-form{padding:30px;border:1px solid var(--line);border-radius:12px;background:#fff;box-shadow:var(--shadow)}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:13px}.lead-form label{display:block;margin:0 0 6px;color:#4f5863;font-size:11px;font-weight:800}.lead-form input,.lead-form select,.lead-form textarea{width:100%;margin-bottom:14px;border:1px solid #d9dde2;border-radius:8px;background:#fff;outline:0}.lead-form input,.lead-form select{height:48px;padding:0 13px}.lead-form textarea{min-height:120px;padding:12px 13px;resize:vertical}.lead-form input:focus,.lead-form select:focus,.lead-form textarea:focus{border-color:var(--red);box-shadow:0 0 0 3px rgba(228,43,67,.1)}.form-status{min-height:20px;margin-top:12px;font-size:12px}.login-panel{max-width:460px;margin:0 auto}.site-footer{padding:60px 0 26px;border-top:1px solid var(--line);background:#fff}.footer-grid{display:grid;grid-template-columns:1.4fr repeat(4,1fr);gap:36px}.footer-brand p{max-width:320px;color:var(--muted);font-size:12px;line-height:1.6}.site-footer h4{margin:0 0 14px;font-size:11px}.site-footer a{display:block;margin:9px 0;color:#69727d;font-size:11px}.footer-bottom{display:flex;justify-content:space-between;gap:20px;margin-top:42px;padding-top:20px;border-top:1px solid var(--line);color:#838b95;font-size:10px}
@media(max-width:1080px){.main-nav{display:none}.menu-button{display:block}.hero-grid,.split,.page-grid,.form-wrap{grid-template-columns:1fr}.hero-grid{gap:48px}.hero-copy{text-align:center}.hero h1,.hero p{margin-left:auto;margin-right:auto}.hero-actions,.hero-badges{justify-content:center}.product-shell{max-width:760px;margin:0 auto}.feature-grid{grid-template-columns:repeat(2,1fr)}.outcome-grid{grid-template-columns:repeat(2,1fr)}.outcome{border-bottom:1px solid #303843}.ecosystem-grid{grid-template-columns:repeat(2,1fr)}.footer-grid{grid-template-columns:1.4fr repeat(2,1fr)}}
@media(max-width:720px){.container{width:min(100% - 32px,1240px)}.site-header,.header-inner{height:70px}.login-link,.header-actions>.button{display:none}.hero{padding:58px 0}.hero h1{font-size:48px;letter-spacing:-3px}.hero-badges{grid-template-columns:1fr 1fr}.product-layout{grid-template-columns:88px 1fr}.product-sidebar a{padding:8px 6px;font-size:8px}.metric-grid{grid-template-columns:1fr 1fr}.product-lower{grid-template-columns:1fr}.section{padding:72px 0}.feature-grid,.ecosystem-grid,.plan-grid{grid-template-columns:1fr}.outcome-grid{grid-template-columns:1fr}.outcome{border-right:0}.split{gap:36px}.cta-grid{grid-template-columns:1fr}.cta-actions{display:grid}.content-grid{grid-template-columns:1fr}.side-nav{display:none}.form-row{grid-template-columns:1fr}.footer-grid{grid-template-columns:1fr 1fr}.footer-brand{grid-column:1/-1}.footer-bottom{display:grid}.logo-row{grid-template-columns:repeat(3,1fr)}}
@media(max-width:480px){.hero h1{font-size:41px}.hero-actions{display:grid}.hero-actions .button{width:100%}.product-shell{margin-inline:-8px}.product-layout{grid-template-columns:72px 1fr}.product-main{padding:12px}.metric{padding:10px}.metric strong{font-size:15px}.footer-grid{grid-template-columns:1fr}.footer-brand{grid-column:auto}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.button,.feature-card{transition:none}}
`;
